[
  {
    "id": "04bd2dcf-0e16-422d-8bcb-56f604e10ae9",
    "project": "Tabilog",
    "timestamp": "2025-09-28 15:43:27",
    "errorType": "DATABASE",
    "errorMessage": "HikariPool-2 - Failed to validate connection com.mysql.cj.jdbc.ConnectionImpl@6b002e1d (No operations allowed after connection closed.). Possibly consider using a shorter maxLifetime value.",
    "summary": "HikariPool-2 - Failed to validate connection com.mysql.cj.jdbc.ConnectionImpl@6b002e1d (No operat...",
    "stackTrace": [],
    "rawText": "HikariPool-2 - Failed to validate connection com.mysql.cj.jdbc.ConnectionImpl@6b002e1d (No operations allowed after connection closed.). Possibly consider using a shorter maxLifetime value.\n HikariPool-2 - Failed to validate connection com.mysql.cj.jdbc.ConnectionImpl@54764a28 (No operations allowed after connection closed.). Possibly consider using a shorter maxLifetime value.",
    "resolved": false,
    "status": "PENDING"
  },
  {
    "id": "12048be3-c70c-4be7-a2e9-2fdd23f0ad47",
    "project": "Tabilog",
    "timestamp": "2025-09-28 15:43:36",
    "errorType": "DATABASE",
    "errorMessage": "HikariPool-2 - Failed to validate connection com.mysql.cj.jdbc.ConnectionImpl@4a5d415c (No operations allowed after connection closed.). Possibly consider using a shorter maxLifetime value.",
    "summary": "HikariPool-2 - Failed to validate connection com.mysql.cj.jdbc.ConnectionImpl@4a5d415c (No operat...",
    "stackTrace": [],
    "rawText": "HikariPool-2 - Failed to validate connection com.mysql.cj.jdbc.ConnectionImpl@4a5d415c (No operations allowed after connection closed.). Possibly consider using a shorter maxLifetime value.\n HikariPool-2 - Failed to validate connection com.mysql.cj.jdbc.ConnectionImpl@1caf302a (No operations allowed after connection closed.). Possibly consider using a shorter maxLifetime value.",
    "resolved": false,
    "status": "PENDING"
  },
  {
    "id": "ff8eb664-c4fd-47a4-b30d-c5996700eb15",
    "project": "Tabilog",
    "timestamp": "2025-09-28 15:43:49",
    "errorType": "DATABASE",
    "errorMessage": "HikariPool-2 - Failed to validate connection com.mysql.cj.jdbc.ConnectionImpl@5dd4e7a2 (No operations allowed after connection closed.). Possibly consider using a shorter maxLifetime value.",
    "summary": "HikariPool-2 - Failed to validate connection com.mysql.cj.jdbc.ConnectionImpl@5dd4e7a2 (No operat...",
    "stackTrace": [],
    "rawText": "HikariPool-2 - Failed to validate connection com.mysql.cj.jdbc.ConnectionImpl@5dd4e7a2 (No operations allowed after connection closed.). Possibly consider using a shorter maxLifetime value.\n HikariPool-2 - Failed to validate connection com.mysql.cj.jdbc.ConnectionImpl@4c7f7689 (No operations allowed after connection closed.). Possibly consider using a shorter maxLifetime value.",
    "resolved": false,
    "status": "PENDING"
  },
  {
    "id": "1421689f-a199-43d9-8f5c-b369ffb68327",
    "project": "Tabilog",
    "timestamp": "2025-09-28 15:43:59",
    "errorType": "DATABASE",
    "errorMessage": "HikariPool-2 - Failed to validate connection com.mysql.cj.jdbc.ConnectionImpl@1f8bf08 (No operations allowed after connection closed.). Possibly consider using a shorter maxLifetime value.",
    "summary": "HikariPool-2 - Failed to validate connection com.mysql.cj.jdbc.ConnectionImpl@1f8bf08 (No operati...",
    "stackTrace": [],
    "rawText": "HikariPool-2 - Failed to validate connection com.mysql.cj.jdbc.ConnectionImpl@1f8bf08 (No operations allowed after connection closed.). Possibly consider using a shorter maxLifetime value.\n HikariPool-2 - Failed to validate connection com.mysql.cj.jdbc.ConnectionImpl@3ec5c530 (No operations allowed after connection closed.). Possibly consider using a shorter maxLifetime value.",
    "resolved": false,
    "status": "PENDING"
  },
  {
    "id": "149107e6-ba9a-40a9-a48f-39e1656fe061",
    "project": "Tabilog",
    "timestamp": "2025-09-28 15:44:06",
    "errorType": "DATABASE",
    "errorMessage": "HikariPool-2 - Failed to validate connection com.mysql.cj.jdbc.ConnectionImpl@2f322fdb (No operations allowed after connection closed.). Possibly consider using a shorter maxLifetime value.",
    "summary": "HikariPool-2 - Failed to validate connection com.mysql.cj.jdbc.ConnectionImpl@2f322fdb (No operat...",
    "stackTrace": [],
    "rawText": "HikariPool-2 - Failed to validate connection com.mysql.cj.jdbc.ConnectionImpl@2f322fdb (No operations allowed after connection closed.). Possibly consider using a shorter maxLifetime value.\n HikariPool-2 - Failed to validate connection com.mysql.cj.jdbc.ConnectionImpl@7fba1bb1 (No operations allowed after connection closed.). Possibly consider using a shorter maxLifetime value.",
    "resolved": false,
    "status": "PENDING"
  },
  {
    "id": "c9de29e0-8bb9-4351-9852-ee077d209670",
    "project": "Tabilog",
    "timestamp": "2025-09-28 16:06:24",
    "errorType": "SPRING_FRAMEWORK",
    "errorMessage": "Detected org.springframework.web.servlet.view.DefaultRequestToViewNameTranslator@2c83823f",
    "summary": "Detected org.springframework.web.servlet.view.DefaultRequestToViewNameTranslator@2c83823f",
    "stackTrace": [],
    "rawText": "Detected org.springframework.web.servlet.view.DefaultRequestToViewNameTranslator@2c83823f\n Detected org.springframework.web.servlet.support.SessionFlashMapManager@10fa17e3",
    "resolved": false,
    "status": "PENDING"
  },
  {
    "id": "16ba78ff-0965-47ca-9675-bafbe3fba4de",
    "project": "Tabilog",
    "timestamp": "2025-09-28 16:06:50",
    "errorType": "UNKNOWN",
    "errorMessage": "ERRORERRORERRORERROR        p1_0.created_at desc",
    "summary": "ERRORERRORERRORERROR        p1_0.created_at desc",
    "stackTrace": [],
    "rawText": "ERRORERRORERRORERROR        p1_0.created_at desc\n        e1_0.updated_at",
    "resolved": false,
    "status": "PENDING"
  },
  {
    "id": "c2155e06-6ba5-4df1-83e6-94d5cc7ea52b",
    "project": "Tabilog",
    "timestamp": "2025-09-28 16:07:35",
    "errorType": "UNKNOWN",
    "errorMessage": "p1_0.created_at desc",
    "summary": "p1_0.created_at desc",
    "stackTrace": [],
    "rawText": "p1_0.created_at desc\n        e1_0.updated_at",
    "resolved": false,
    "status": "PENDING"
  },
  {
    "id": "f3646d43-89bb-4633-a52b-68ff97c476e8",
    "project": "Tabilog",
    "timestamp": "2025-09-28 16:08:02",
    "errorType": "UNKNOWN",
    "errorMessage": "[JWT] expired: JWT expired 15 milliseconds ago at 2025-09-28T07:08:02.000Z. Current time: 2025-09-28T07:08:02.015Z. Allowed clock skew: 0 milliseconds.",
    "summary": "[JWT] expired: JWT expired 15 milliseconds ago at 2025-09-28T07:08:02.000Z. Current time: 2025-09...",
    "stackTrace": [],
    "rawText": "[JWT] expired: JWT expired 15 milliseconds ago at 2025-09-28T07:08:02.000Z. Current time: 2025-09-28T07:08:02.015Z. Allowed clock skew: 0 milliseconds.\n JWT expired: JWT expired 15 milliseconds ago at 2025-09-28T07:08:02.000Z. Current time: 2025-09-28T07:08:02.015Z. Allowed clock skew: 0 milliseconds.",
    "resolved": false,
    "status": "PENDING"
  },
  {
    "id": "ef105b7a-183c-42c3-86f0-d2ee0bea121f",
    "project": "Tabilog",
    "timestamp": "2025-09-28 16:09:05",
    "errorType": "UNKNOWN",
    "errorMessage": "JWT expired: JWT expired 66 milliseconds ago at 2025-09-28T07:09:05.000Z. Current time: 2025-09-28T07:09:05.066Z. Allowed clock skew: 0 milliseconds.",
    "summary": "JWT expired: JWT expired 66 milliseconds ago at 2025-09-28T07:09:05.000Z. Current time: 2025-09-2...",
    "stackTrace": [],
    "rawText": "JWT expired: JWT expired 66 milliseconds ago at 2025-09-28T07:09:05.000Z. Current time: 2025-09-28T07:09:05.066Z. Allowed clock skew: 0 milliseconds.\n [JWT] expired: JWT expired 66 milliseconds ago at 2025-09-28T07:09:05.000Z. Current time: 2025-09-28T07:09:05.066Z. Allowed clock skew: 0 milliseconds.",
    "resolved": false,
    "status": "PENDING"
  },
  {
    "id": "7795e66f-1f73-4b58-a47b-3a4120e95db2",
    "project": "Tabilog",
    "timestamp": "2025-09-28 16:09:32",
    "errorType": "UNKNOWN",
    "errorMessage": ".m.m.a.ExceptionHandlerExceptionResolver Using @ExceptionHandler com.ikuzo.tabilog.global.GlobalExceptionHandler#handleBadCredentialsException(BadCredentialsException)",
    "summary": ".m.m.a.ExceptionHandlerExceptionResolver Using @ExceptionHandler com.ikuzo.tabilog.global.GlobalE...",
    "stackTrace": [],
    "rawText": ".m.m.a.ExceptionHandlerExceptionResolver Using @ExceptionHandler com.ikuzo.tabilog.global.GlobalExceptionHandler#handleBadCredentialsException(BadCredentialsException)\n Writing [ErrorResponse(status\u003d401, error\u003dINVALID_CREDENTIALS, message\u003d아이디(또는 이메일) 또는 비밀번호가 올바르지 않습니다., timest (truncated)...]",
    "resolved": false,
    "status": "PENDING"
  },
  {
    "id": "649986b7-ac8c-427a-8fe3-057d843879e6",
    "project": "Tabilog",
    "timestamp": "2025-09-28 16:09:34",
    "errorType": "SPRING_FRAMEWORK",
    "exceptionClass": "org.springframework.security.authentication.BadCredentialsException",
    "errorMessage": "자격 증명에 실패하였습니다.]",
    "summary": "org.springframework.security.authentication.BadCredentialsException: 자격 증명에 실패하였습니다.]",
    "stackTrace": [],
    "rawText": ".m.m.a.ExceptionHandlerExceptionResolver Resolved [org.springframework.security.authentication.BadCredentialsException: 자격 증명에 실패하였습니다.]\n.m.m.a.ExceptionHandlerExceptionResolver",
    "resolved": false,
    "status": "PENDING"
  },
  {
    "id": "0f61ccb4-78b5-4219-ae6a-e8531b23f1f2",
    "project": "Tabilog",
    "timestamp": "2025-09-28 16:09:34",
    "errorType": "SPRING_FRAMEWORK",
    "exceptionClass": "org.springframework.security.authentication.BadCredentialsException",
    "errorMessage": "자격 증명에 실 Writing [ErrorResponse(status\u003d401, error\u003dINVALID_CREDENTIALS, message\u003d아이디(또는 이메일) 또는 비밀번호가 올바르지 않습니다., timest (truncated)...]",
    "summary": "org.springframework.security.authentication.BadCredentialsException: 자격 증명에 실 Writing [ErrorResponse(status\u003d401, error\u003dINVALID_CREDENTIALS, message\u003d아이디(또는 이메일) 또는 비밀번...",
    "stackTrace": [],
    "rawText": ".m.m.a.ExceptionHandlerExceptionResolver Resolved [org.springframework.security.authentication.BadCredentialsException: 자격 증명에 실 Writing [ErrorResponse(status\u003d401, error\u003dINVALID_CREDENTIALS, message\u003d아이디(또는 이메일) 또는 비밀번호가 올바르지 않습니다., timest (truncated)...]\n.m.m.a.ExceptionHandlerExceptionResolver",
    "resolved": false,
    "status": "PENDING"
  },
  {
    "id": "b4c93605-e3ef-4585-aebf-cc766ea7f7b1",
    "project": "Tabilog",
    "timestamp": "2025-09-28 16:09:39",
    "errorType": "SPRING_FRAMEWORK",
    "exceptionClass": "org.springframework.security.authentication.BadCredentialsException",
    "errorMessage": "자격 증명에 실패하였습니다.]",
    "summary": "org.springframework.security.authentication.BadCredentialsException: 자격 증명에 실패하였습니다.]",
    "stackTrace": [],
    "rawText": "Resolved [org.springframework.security.authentication.BadCredentialsException: 자격 증명에 실패하였습니다.]\n Using @ExceptionHandler com.ikuzo.tabilog.global.GlobalExceptionHandler#handleBadCredentialsException(BadCredentialsException)",
    "resolved": false,
    "status": "PENDING"
  },
  {
    "id": "993ec682-c79d-438f-81f5-140f557531ed",
    "project": "Tabilog",
    "timestamp": "2025-09-28 16:09:39",
    "errorType": "UNKNOWN",
    "errorMessage": ".m.m.a.ExceptionHandlerExceptionResolver Writing [ErrorResponse(status\u003d401, error\u003dINVALID_CREDENTIALS, message\u003d아이디(또는 이메일) 또는 비밀번호가 올바르지 않습니다., timest (truncated)...]",
    "summary": ".m.m.a.ExceptionHandlerExceptionResolver Writing [ErrorResponse(status\u003d401, error\u003dINVALID_CREDENT...",
    "stackTrace": [],
    "rawText": ".m.m.a.ExceptionHandlerExceptionResolver Writing [ErrorResponse(status\u003d401, error\u003dINVALID_CREDENTIALS, message\u003d아이디(또는 이메일) 또는 비밀번호가 올바르지 않습니다., timest (truncated)...]\n.m.m.a.ExceptionHandlerExceptionResolver",
    "resolved": false,
    "status": "PENDING"
  },
  {
    "id": "064b2317-fda8-4756-8437-0b722cf57d88",
    "project": "Tabilog",
    "timestamp": "2025-09-28 16:09:43",
    "errorType": "SPRING_FRAMEWORK",
    "exceptionClass": "org.springframework.security.authentication.BadCredentialsException",
    "errorMessage": "자격 증명에 실패하였습니다.]",
    "summary": "org.springframework.security.authentication.BadCredentialsException: 자격 증명에 실패하였습니다.]",
    "stackTrace": [],
    "rawText": "Resolved [org.springframework.security.authentication.BadCredentialsException: 자격 증명에 실패하였습니다.]\n.m.m.a.ExceptionHandlerExceptionResolver Using @ExceptionHandler com.ikuzo.tabilog.global.GlobalExceptionHandler#handleBadCredentialsException(BadCredentialsException)",
    "resolved": false,
    "status": "PENDING"
  },
  {
    "id": "dde66100-2e39-4bd8-8657-61663e2114b5",
    "project": "Tabilog",
    "timestamp": "2025-09-28 16:09:43",
    "errorType": "UNKNOWN",
    "errorMessage": "Writing [ErrorResponse(status\u003d401, error\u003dINVALID_CREDENTIALS, message\u003d아이디(또는 이메일) 또는 비밀번호가 올바르지 않습니다., timest (truncated)...]",
    "summary": "Writing [ErrorResponse(status\u003d401, error\u003dINVALID_CREDENTIALS, message\u003d아이디(또는 이메일) 또는 비밀번호가 올바르지 않...",
    "stackTrace": [],
    "rawText": "Writing [ErrorResponse(status\u003d401, error\u003dINVALID_CREDENTIALS, message\u003d아이디(또는 이메일) 또는 비밀번호가 올바르지 않습니다., timest (truncated)...]\n.m.m.a.ExceptionHandlerExceptionResolver",
    "resolved": false,
    "status": "PENDING"
  },
  {
    "id": "efe57c1a-96ed-4450-bc73-27b523c06cf2",
    "project": "Tabilog",
    "timestamp": "2025-09-28 16:09:49",
    "errorType": "SPRING_FRAMEWORK",
    "exceptionClass": "org.springframework.security.authentication.BadCredentialsException",
    "errorMessage": "자격 증명에 실패하였습니다.]",
    "summary": "org.springframework.security.authentication.BadCredentialsException: 자격 증명에 실패하였습니다.]",
    "stackTrace": [],
    "rawText": "Resolved [org.springframework.security.authentication.BadCredentialsException: 자격 증명에 실패하였습니다.]\n.m.m.a.ExceptionHandlerExceptionResolverog.global.GlobalExceptionHandler#handleBadCredentialsException(BadCredentialsException)\ntialsException(BadCredentialsException)",
    "resolved": false,
    "status": "PENDING"
  },
  {
    "id": "af86d1e8-c1d4-4ce3-be87-93aee3b3dba3",
    "project": "Tabilog",
    "timestamp": "2025-09-28 16:09:49",
    "errorType": "UNKNOWN",
    "errorMessage": "Writing [ErrorResponse(status\u003d401, error\u003dINVALID_CREDENTIALS, message\u003d아이디(또는 이메일) 또는 비밀번호가 올바르지 않습니다., timest (truncated)...]",
    "summary": "Writing [ErrorResponse(status\u003d401, error\u003dINVALID_CREDENTIALS, message\u003d아이디(또는 이메일) 또는 비밀번호가 올바르지 않...",
    "stackTrace": [],
    "rawText": "Writing [ErrorResponse(status\u003d401, error\u003dINVALID_CREDENTIALS, message\u003d아이디(또는 이메일) 또는 비밀번호가 올바르지 않습니다., timest (truncated)...]\n.m.m.a.ExceptionHandlerExceptionResolver",
    "resolved": false,
    "status": "PENDING"
  },
  {
    "id": "0e44e69a-c6a6-45cb-9d46-d6e7e5f018c7",
    "project": "Tabilog",
    "timestamp": "2025-09-28 16:09:57",
    "errorType": "SPRING_FRAMEWORK",
    "exceptionClass": "org.springframework.security.authentication.BadCredentialsException",
    "errorMessage": "자격 증명에 실패하였습니다.]",
    "summary": "org.springframework.security.authentication.BadCredentialsException: 자격 증명에 실패하였습니다.]",
    "stackTrace": [],
    "rawText": "Resolved [org.springframework.security.authentication.BadCredentialsException: 자격 증명에 실패하였습니다.]\n.m.m.a.ExceptionHandlerExceptionResolver Using @ExceptionHandler com.ikuzo.tabilog.global.GlobalExceptionHandler#handleBadCredentialsException(BadCredentialsException)",
    "resolved": false,
    "status": "PENDING"
  },
  {
    "id": "1cd6509c-10e2-42ba-952d-78e53d80a9a8",
    "project": "Tabilog",
    "timestamp": "2025-09-28 16:09:57",
    "errorType": "UNKNOWN",
    "errorMessage": "Writing [ErrorResponse(status\u003d401, error\u003dINVALID_CREDENTIALS, message\u003d아이디(또는 이메일) 또는 비밀번호가 올바르지 않습니다., timest (truncated)...]",
    "summary": "Writing [ErrorResponse(status\u003d401, error\u003dINVALID_CREDENTIALS, message\u003d아이디(또는 이메일) 또는 비밀번호가 올바르지 않...",
    "stackTrace": [],
    "rawText": "Writing [ErrorResponse(status\u003d401, error\u003dINVALID_CREDENTIALS, message\u003d아이디(또는 이메일) 또는 비밀번호가 올바르지 않습니다., timest (truncated)...]\n.m.m.a.ExceptionHandlerExceptionResolver",
    "resolved": false,
    "status": "PENDING"
  },
  {
    "id": "cbcc00b2-0c9b-4581-a1fe-5f0ad46899c8",
    "project": "Tabilog",
    "timestamp": "2025-09-28 16:10:09",
    "errorType": "SPRING_FRAMEWORK",
    "exceptionClass": "org.springframework.security.authentication.BadCredentialsException",
    "errorMessage": "자격 증명에 실패하였습니다.]",
    "summary": "org.springframework.security.authentication.BadCredentialsException: 자격 증명에 실패하였습니다.]",
    "stackTrace": [],
    "rawText": "Resolved [org.springframework.security.authentication.BadCredentialsException: 자격 증명에 실패하였습니다.]\n.m.m.a.ExceptionHandlerExceptionResolver",
    "resolved": false,
    "status": "PENDING"
  },
  {
    "id": "191cb2f3-ff3b-48e8-a4a4-764a8bff3f94",
    "project": "Tabilog",
    "timestamp": "2025-09-28 16:10:09",
    "errorType": "UNKNOWN",
    "errorMessage": "Using @ExceptionHandler com.ikuzo.tabilog.global.GlobalExceptionHandler#handleBadCredentialsException(BadCredentialsException)",
    "summary": "Using @ExceptionHandler com.ikuzo.tabilog.global.GlobalExceptionHandler#handleBadCredentialsExcep...",
    "stackTrace": [],
    "rawText": "Using @ExceptionHandler com.ikuzo.tabilog.global.GlobalExceptionHandler#handleBadCredentialsException(BadCredentialsException)\n Writing [ErrorResponse(status\u003d401, error\u003dINVALID_CREDENTIALS, message\u003d아이디(또는 이메일) 또는 비밀번호가 올바르지 않습니다., timest (truncated)...]",
    "resolved": false,
    "status": "PENDING"
  },
  {
    "id": "9e187973-df1e-4f09-91e8-23f96ddcbb8c",
    "project": "Tabilog",
    "timestamp": "2025-09-28 16:10:16",
    "errorType": "SPRING_FRAMEWORK",
    "exceptionClass": "org.springframework.security.authentication.BadCredentialsException",
    "errorMessage": "자격 증명에 실패하였습니다.]",
    "summary": "org.springframework.security.authentication.BadCredentialsException: 자격 증명에 실패하였습니다.]",
    "stackTrace": [],
    "rawText": ".m.m.a.ExceptionHandlerExceptionResolver Resolved [org.springframework.security.authentication.BadCredentialsException: 자격 증명에 실패하였습니다.]\n Using @ExceptionHandler com.ikuzo.tabilog.global.GlobalExceptionHandler#handleBadCredentialsException(BadCredentialsException)",
    "resolved": false,
    "status": "PENDING"
  },
  {
    "id": "56dc8c48-6e81-41fc-8262-e482b2b8a6e8",
    "project": "Tabilog",
    "timestamp": "2025-09-28 16:10:16",
    "errorType": "UNKNOWN",
    "errorMessage": ".m.m.a.ExceptionHandlerExceptionResolver Writing [ErrorResponse(status\u003d401, error\u003dINVALID_CREDENTIALS, message\u003d아이디(또는 이메일) 또는 비밀번호가 올바르지 않습니다., timest (truncated)...]",
    "summary": ".m.m.a.ExceptionHandlerExceptionResolver Writing [ErrorResponse(status\u003d401, error\u003dINVALID_CREDENT...",
    "stackTrace": [],
    "rawText": ".m.m.a.ExceptionHandlerExceptionResolver Writing [ErrorResponse(status\u003d401, error\u003dINVALID_CREDENTIALS, message\u003d아이디(또는 이메일) 또는 비밀번호가 올바르지 않습니다., timest (truncated)...]\n.m.m.a.ExceptionHandlerExceptionResolver",
    "resolved": false,
    "status": "PENDING"
  },
  {
    "id": "f5e4fac0-898f-4ce1-84e5-3d229d7f5826",
    "project": "Tabilog",
    "timestamp": "2025-09-28 16:10:17",
    "errorType": "SPRING_FRAMEWORK",
    "exceptionClass": "org.springframework.security.authentication.BadCredentialsException",
    "errorMessage": "자격 증명에 실패하였습니다.]",
    "summary": "org.springframework.security.authentication.BadCredentialsException: 자격 증명에 실패하였습니다.]",
    "stackTrace": [],
    "rawText": "Resolved [org.springframework.security.authentication.BadCredentialsException: 자격 증명에 실패하였습니다.]\n.m.m.a.ExceptionHandlerExceptionResolverog.global.GlobalExceptionHandler#handleBadCredentialsException(BadCredentialsException)\ntialsException(BadCredentialsException)",
    "resolved": false,
    "status": "PENDING"
  },
  {
    "id": "4a0a88db-698f-4b2e-8328-5d76b5eb0460",
    "project": "Tabilog",
    "timestamp": "2025-09-28 16:10:17",
    "errorType": "SPRING_FRAMEWORK",
    "exceptionClass": "org.springframework.security.authentication.BadCredentialsException",
    "errorMessage": "자격 증명에 실패하였습니다.]",
    "summary": "org.springframework.security.authentication.BadCredentialsException: 자격 증명에 실패하였습니다.]",
    "stackTrace": [],
    "rawText": "Resolved [org.springframework.security.authentication.BadCredentialsException: 자격 증명에 실패하였습니다.]\n.m.m.a.ExceptionHandlerExceptionResolverog.global.GlobalExceptionHandler#handleBadCredentialsException(BadCredentialsException)\ntialsException(BadCredentialsException)",
    "resolved": false,
    "status": "PENDING"
  },
  {
    "id": "5d4a6f8e-022b-4774-9743-4a564413aa6d",
    "project": "Tabilog",
    "timestamp": "2025-09-28 16:10:17",
    "errorType": "UNKNOWN",
    "errorMessage": "Writing [ErrorResponse(status\u003d401, error\u003dINVALID_CREDENTIALS, message\u003d아이디(또는 이메일) 또는 비밀번호가 올바르지 않습니다., timest (truncated)...]",
    "summary": "Writing [ErrorResponse(status\u003d401, error\u003dINVALID_CREDENTIALS, message\u003d아이디(또는 이메일) 또는 비밀번호가 올바르지 않...",
    "stackTrace": [],
    "rawText": "Writing [ErrorResponse(status\u003d401, error\u003dINVALID_CREDENTIALS, message\u003d아이디(또는 이메일) 또는 비밀번호가 올바르지 않습니다., timest (truncated)...]\n.m.m.a.ExceptionHandlerExceptionResolver",
    "resolved": false,
    "status": "PENDING"
  },
  {
    "id": "928e2b91-027c-4c2f-8671-d847543460b5",
    "project": "Tabilog",
    "timestamp": "2025-09-28 16:10:18",
    "errorType": "SPRING_FRAMEWORK",
    "exceptionClass": "org.springframework.security.authentication.BadCredentialsException",
    "errorMessage": "자격 증명에 실패하였습니다.]",
    "summary": "org.springframework.security.authentication.BadCredentialsException: 자격 증명에 실패하였습니다.]",
    "stackTrace": [],
    "rawText": "Resolved [org.springframework.security.authentication.BadCredentialsException: 자격 증명에 실패하였습니다.]\n Using @ExceptionHandler com.ikuzo.tabilog.global.GlobalExceptionHandler#handleBadCredentialsException(BadCredentialsException)\ntialsException(BadCredentialsException)",
    "resolved": false,
    "status": "PENDING"
  },
  {
    "id": "15da5aea-ab13-4eff-b21c-6f9a67015d0d",
    "project": "Tabilog",
    "timestamp": "2025-09-28 16:10:18",
    "errorType": "UNKNOWN",
    "errorMessage": "Writing [ErrorResponse(status\u003d401, error\u003dINVALID_CREDENTIALS, message\u003d아이디(또는 이메일) 또는 비밀번호가 올바르지 않습니다., timest (truncated)...]",
    "summary": "Writing [ErrorResponse(status\u003d401, error\u003dINVALID_CREDENTIALS, message\u003d아이디(또는 이메일) 또는 비밀번호가 올바르지 않...",
    "stackTrace": [],
    "rawText": "Writing [ErrorResponse(status\u003d401, error\u003dINVALID_CREDENTIALS, message\u003d아이디(또는 이메일) 또는 비밀번호가 올바르지 않습니다., timest (truncated)...]\n.m.m.a.ExceptionHandlerExceptionResolver",
    "resolved": false,
    "status": "PENDING"
  },
  {
    "id": "8088750b-d0c5-4883-a27d-edf04f7d11bf",
    "project": "Tabilog",
    "timestamp": "2025-09-28 16:10:27",
    "errorType": "SPRING_FRAMEWORK",
    "exceptionClass": "org.springframework.security.authentication.BadCredentialsException",
    "errorMessage": "자격 증명에 실패하였습니다.]",
    "summary": "org.springframework.security.authentication.BadCredentialsException: 자격 증명에 실패하였습니다.]",
    "stackTrace": [],
    "rawText": "Resolved [org.springframework.security.authentication.BadCredentialsException: 자격 증명에 실패하였습니다.]\n.m.m.a.ExceptionHandlerExceptionResolver Using @ExceptionHandler com.ikuzo.tabilog.global.GlobalExceptionHandler#handleBadCredentialsException(BadCredentialsException)",
    "resolved": false,
    "status": "PENDING"
  },
  {
    "id": "4ef0c3b4-db2d-4650-bd6b-319ba0339f7a",
    "project": "Tabilog",
    "timestamp": "2025-09-28 16:10:27",
    "errorType": "UNKNOWN",
    "errorMessage": "Writing [ErrorResponse(status\u003d401, error\u003dINVALID_CREDENTIALS, message\u003d아이디(또는 이메일) 또는 비밀번호가 올바르지 않습니다., timest (truncated)...]",
    "summary": "Writing [ErrorResponse(status\u003d401, error\u003dINVALID_CREDENTIALS, message\u003d아이디(또는 이메일) 또는 비밀번호가 올바르지 않...",
    "stackTrace": [],
    "rawText": "Writing [ErrorResponse(status\u003d401, error\u003dINVALID_CREDENTIALS, message\u003d아이디(또는 이메일) 또는 비밀번호가 올바르지 않습니다., timest (truncated)...]\n.m.m.a.ExceptionHandlerExceptionResolver",
    "resolved": false,
    "status": "PENDING"
  },
  {
    "id": "1e10b0be-7493-4b1b-bade-e295365d7027",
    "project": "Tabilog",
    "timestamp": "2025-09-28 16:10:41",
    "errorType": "SPRING_FRAMEWORK",
    "exceptionClass": "org.springframework.security.authentication.BadCredentialsException",
    "errorMessage": "자격 증명에 실패하였습니다.]",
    "summary": "org.springframework.security.authentication.BadCredentialsException: 자격 증명에 실패하였습니다.]",
    "stackTrace": [],
    "rawText": "Resolved [org.springframework.security.authentication.BadCredentialsException: 자격 증명에 실패하였습니다.]\n.m.m.a.ExceptionHandlerExceptionResolver Using @ExceptionHandler com.ikuzo.tabilog.global.GlobalExceptionHandler#handleBadCredentialsException(BadCredentialsException)",
    "resolved": false,
    "status": "PENDING"
  },
  {
    "id": "a51cdf43-5417-4ced-9a0b-00e6de3e50cd",
    "project": "Tabilog",
    "timestamp": "2025-09-28 16:10:41",
    "errorType": "UNKNOWN",
    "errorMessage": "Writing [ErrorResponse(status\u003d401, error\u003dINVALID_CREDENTIALS, message\u003d아이디(또는 이메일) 또는 비밀번호가 올바르지 않습니다., timest (truncated)...]",
    "summary": "Writing [ErrorResponse(status\u003d401, error\u003dINVALID_CREDENTIALS, message\u003d아이디(또는 이메일) 또는 비밀번호가 올바르지 않...",
    "stackTrace": [],
    "rawText": "Writing [ErrorResponse(status\u003d401, error\u003dINVALID_CREDENTIALS, message\u003d아이디(또는 이메일) 또는 비밀번호가 올바르지 않습니다., timest (truncated)...]\n.m.m.a.ExceptionHandlerExceptionResolver",
    "resolved": false,
    "status": "PENDING"
  },
  {
    "id": "eb7dc203-24fd-4b60-98e6-d9fc536008da",
    "project": "Tabilog",
    "timestamp": "2025-09-28 16:35:10",
    "errorType": "SPRING_FRAMEWORK",
    "exceptionClass": "org.springframework.security.authentication.BadCredentialsException",
    "errorMessage": "자격 증명에 실패하였습니다.]",
    "summary": "org.springframework.security.authentication.BadCredentialsException: 자격 증명에 실패하였습니다.]",
    "stackTrace": [],
    "rawText": "Resolved [org.springframework.security.authentication.BadCredentialsException: 자격 증명에 실패하였습니다.]\n        p1_0.created_at desc",
    "resolved": false,
    "status": "PENDING"
  },
  {
    "id": "c28fd72f-de60-416d-8439-46d6f389b6c3",
    "project": "Tabilog",
    "timestamp": "2025-09-28 16:35:20",
    "errorType": "UNKNOWN",
    "errorMessage": "e1_0.updated_at",
    "summary": "e1_0.updated_at",
    "stackTrace": [],
    "rawText": "e1_0.updated_at \n JWT expired: JWT expired 54 milliseconds ago at 2025-09-28T07:35:20.000Z. Current time: 2025-09-28T07:35:20.054Z. Allowed clock skew: 0 milliseconds.\n [JWT] expired: JWT expired 54 milliseconds ago at 2025-09-28T07:35:20.000Z. Current time: 2025-09-28T07:35:20.054Z. Allowed clock skew: 0 milliseconds.",
    "resolved": false,
    "status": "PENDING"
  },
  {
    "id": "db39f2c6-b2b5-4427-9345-6a072a1861b4",
    "project": "Tabilog",
    "timestamp": "2025-09-28 16:38:31",
    "errorType": "DATABASE",
    "errorMessage": "Tomcat initialized with port 8080 (http)",
    "summary": "Tomcat initialized with port 8080 (http)",
    "stackTrace": [],
    "rawText": "Tomcat initialized with port 8080 (http)\n HikariPool-3 - Added connection com.mysql.cj.jdbc.ConnectionImpl@c611805",
    "resolved": false,
    "status": "PENDING"
  },
  {
    "id": "d79fd21c-e0e2-4bc2-846d-0b74d31ac7c7",
    "project": "Tabilog",
    "timestamp": "2025-09-28 16:38:32",
    "errorType": "DATABASE",
    "errorMessage": "org.hibernate.orm.connections.pooling   .m.m.a.ExceptionHandlerExceptionResolver ControllerAdvice beans: 1 @ExceptionHandler, 1 ResponseBodyAdvice",
    "summary": "org.hibernate.orm.connections.pooling   .m.m.a.ExceptionHandlerExceptionResolver ControllerAdvice...",
    "stackTrace": [],
    "rawText": "org.hibernate.orm.connections.pooling   .m.m.a.ExceptionHandlerExceptionResolver ControllerAdvice beans: 1 @ExceptionHandler, 1 ResponseBodyAdvice\n Tomcat started on port 8080 (http) with context path \u0027/\u0027",
    "resolved": false,
    "status": "PENDING"
  },
  {
    "id": "6a4ced8a-0f3d-44f8-ab2a-e2576251c230",
    "project": "Tabilog",
    "timestamp": "2025-09-28 16:40:27",
    "errorType": "SPRING_FRAMEWORK",
    "errorMessage": "Detected org.springframework.web.servlet.view.DefaultRequestToViewNameTranslator@42fde485",
    "summary": "Detected org.springframework.web.servlet.view.DefaultRequestToViewNameTranslator@42fde485",
    "stackTrace": [],
    "rawText": "Detected org.springframework.web.servlet.view.DefaultRequestToViewNameTranslator@42fde485\n Detected org.springframework.web.servlet.support.SessionFlashMapManager@91b4d7e",
    "resolved": false,
    "status": "PENDING"
  },
  {
    "id": "25848f21-8012-4198-85a1-5e1decc99e0b",
    "project": "Tabilog",
    "timestamp": "2025-09-28 16:41:14",
    "errorType": "UNKNOWN",
    "errorMessage": "p1_0.created_at desc",
    "summary": "p1_0.created_at desc",
    "stackTrace": [],
    "rawText": "p1_0.created_at desc\n        e1_0.updated_at",
    "resolved": false,
    "status": "PENDING"
  }
]